### ISSUE TITLE
Small tweaks to the findings section for the home page.

### ISSUE THREAD

**Issue by samswey** [campaignzero/police-scorecard#32]
On the homepage:
- The "7,645" in "7,645" killings by police should be in bold, consistent with the formatting of the other two sections.
- The "2.6x" and "1.3x" should be in bold
- Change the "2016-2018" to "2016-19" (in the section "Only 1 in every 7 complaints were ruled in favor of civilians from 2016-18.")
- Change "Police in America made 14.3x as many arrests for low level offenses as for violent crimes in 2013-2018." to "Police in America made 12x as many arrests for low level offenses as for violent crimes from 2013-2019."

<img width="955" alt="Screen Shot 2020-10-22 at 12 38 26 PM" src="https://user-images.githubusercontent.com/10948944/96903938-72c91d00-1464-11eb-934b-eac510c997b3.png">

**Comment by MasterInTraining23** [comment]
The 14x, representing the factor of misdemeanor arrests compared to violent crime arrests is calculated ([total_low_level_arrests/total_violent_crime_arrests](https://github.com/campaignzero/police-scorecard/blob/5c7b806c4601ed85af0d5ef3498de6a0e88db4b1/app/Helpers.php#L459)). Since that data is based on the state data fetched from the server can we verify that data is up-to-date? When was the data last pushed. 

Side note: I noticed we have specific fields for years up to [2018](https://github.com/campaignzero/police-scorecard/blob/5c7b806c4601ed85af0d5ef3498de6a0e88db4b1/app/Helpers.php#L413) but nothing for 2019, although we are updating our dates to include 2019. Do we need to update other fields on the site to reflect the new data?

**Comment by manifestinteractive** [comment]
@MasterInTraining23 I am working on integrating 2019 data as it did not exist on the API side.  Since I am already working on that, I can pick off this ticket this weekend.
